site_name: Developing with RingCentral
site_url: https://github.com/ringcentral/developing-with-ringcentral
site_favicon: favicon.ico
repo_url: https://github.com/ringcentral/developing-with-ringcentral.git
docs_dir: docs
theme: readthedocs
extra_css: [extra.css]
extra_javascript: [fonts.js]
pages:
- Preface: 'index.md'
- Overview: 'overview.md'
- 'API Rate Limits': 'rate_limits.md'
- 'OAuth 2.0 Authentication & Authorization': 'oauth.md'
- 'Exploring Account & Extension Settings': 'account_extension.md'
- 'Modifying Extension Settings': 'modifying_extension.md'
- 'Modifying Account': 'modifying_account.md'
- 'Call Log':
    - 'Introduction': 'calllog_introduction.md'
    - 'API Basics': 'calllog_api-basics.md'
    - 'Using Detailed Call Log Data': 'calllog_detailed-call-logs.md'
    - 'Call Recordings': 'calllog_call-recordings.md'
    - 'Call Log Synchronization': 'calllog_sync.md'
    - 'Development Concerns': 'calllog_development-concerns.md'
- 'Data Archival':
    - 'Introduction': 'data_archival_introduction.md'
- 'Working with Messages': 'messages.md'
- 'Making Calls': 'making_calls.md'
- 'Conference Calling': 'conference.md'
- 'Call Queues': 'call_queue.md'
- 'Answering Rules': 'answering_rules.md'
- 'Push Notifications': 'notifications.md'
- Webhooks: 'webhooks.md'